FROM bunse/julia-docker-base:0.6.4

MAINTAINER Mirko Bunse <mirko.bunse@cs.tu-dortmund.de>

# REQUIRE and setup.jl are automatically added when inheriting from bunse/julia-docker-base

# here, you can add whatever you like
RUN echo "Build finished"
