ARG JULIA_VERSION
FROM julia:$JULIA_VERSION

MAINTAINER Mirko Bunse <mirko.bunse@cs.tu-dortmund.de>

# copy setup to /opt/julia-docker-base and initialize the package depot
ENV JULIA_PKGDIR=/opt/julia-pkg
ADD julia-docker-base/ /opt/julia-docker-base/
RUN mkdir -p $JULIA_PKGDIR && \
    julia -e 'Pkg.init()'

# the custom tag does not add any files, neither runs any ONBUILD steps

# configure entry point
ENTRYPOINT ["/opt/julia-docker-base/entrypoint.sh"]
CMD ["bash"]
